# src/insider_flow/assets/debug.py
from dagster import asset
import polars as pl

@asset(
    group_name="testing",
)
def test_polars_setup():
    """
    A simple asset to verify Polars and Dagster are working together.
    """
    data = {
        "ticker": ["AAPL", "MSFT", "GOOGL"],
        "price": [150.5, 300.2, 2500.0],
        "is_tech": [True, True, True]
    }
    
    df = pl.DataFrame(data)
    
    # Perform a simple polars operation
    summary = df.select([
        pl.col("ticker"),
        (pl.col("price") * 1.1).alias("projected_price")
    ])
    
    # Dagster logs
    print(f"Created DataFrame with shape: {summary.shape}")
    return summary.to_dicts()


@asset(
    group_name="testing",
)
def sales_data():
    return [100, 200, 300]

@asset(
    group_name="testing",
)
def marketing_data():
    return ["Campaign A", "Campaign B", "Campaign C"]

@asset(
    group_name="testing",
)
def roi_report(sales_data, marketing_data):
    return f"Sales: {sales_data} generated by {marketing_data}"